BaSP-m2023/ferpa-megarocket-server

.eslintrc.js
.husky/pre-commit
babel.config.js
jest.config.js
jest.setup.js
package-lock.json
package.json
src/app.js
src/index.js
tests/activities.test.js
tests/admins.test.js
tests/classes.test.js
tests/members.test.js
tests/subscriptions.test.js
tests/super-admins.test.js
tests/trainers.test.js

all initial setup finished. please review so I can merge it.

BaSP-MR-17: initial setup complete

---

jest.setup.js
src/seeds/admins.js
src/tests/admins.test.js

Unit test with jest to validate the functionality of the get, getById and update methods.
I also created a seed database to be able to test without modifying or damaging the mongoo database.
In the test of the get method includes seeing the code states and validating certain data in the database created in seeds. It also looks for a data by id, it tests the method when passing an invalid id, or an id that does not exist.
In the test of the put method it is validated that a data has been updated correctly using an id, in addition it is tested when passing an invalid id or an id that does not exist in our database in our folder.

BaSP-MR-28: tests admin methods get and update

---

src/seeds/admins.js
src/tests/admins.test.js

I worked on creating a test suite using Jest to verify the correct behavior of the API endpoints for creating and deleting admin. It ensures that the endpoints return the expected status codes and that the database its modified correctly.

 BaSP-MR-19: Tests for admins, POST and DELETE methods

---

src/controllers/members.js
src/models/Member.js
src/seeds/members.js
src/tests/members.test.js

I did 14 test between get, get by id and post, using a seed with 3 mock members

BaSP-MR-23: Test for methods get/getbyid/post for members

---

src/controllers/activites.js
src/seeds/activities.js
src/tests/activities.test.js

I developed all the tests for the activities. Please review it and give me your feedback

BaSP-MR-20: all tests for activities 

---

src/seeds/super-admins.js
src/tests/super-admins.test.js

I create the seed with 3 super admins which have an email and password. Next i developed the tests for get, post, put and delete.

BaSP-MR-18: Create all tests for super admin

---

src/controllers/subscriptions.js

I wasn't able to access to the trainer's data through the class data (subscription.classId.trainerId) because it wasn't populated

BaSP-MR-79: fix subscription controller populate

---

src/models/Class.js

I added all week days to the enum value of the day object in the classes model

MR-82: Fix class model

---

src/models/Activity.js
src/tests/activities.test.js
src/validations/activities.js

Fixed enpoint issues and schema

BaSP-MR-31: Activities Fix enpoint issues and schema

---

src/controllers/members.js
src/models/Activity.js
src/models/Member.js
src/seeds/members.js
src/tests/members.test.js
src/validations/members.js

I reverted previous changes made to activity and member models

BaSP-MR-120: revert changes in activity and member models

---

src/models/Class.js
src/models/Subscription.js
src/tests/subscriptions.test.js
src/validations/activities.js
src/validations/subscriptions.js
src/validations/trainers.js

Fix in validations: Activities, Subscriptions and Classes

BaSP-MR-118: fix in entities

---

package.json
src/helper/firebase/index.js

Firebase implementation:
- New libraries installed (firebase and firebase-admin)
- New auth.js file in controllers
- New auth.js file in routes
- New folder and file authMiddleware.js
- Implementation of fireBase in src/helper/firebase

BaSP-MR-129: Server Setup

---

src/helper/firebase/index.js

Problems with vercel deployment

BaSP-MR-129: Hotfix, problems with vercel

---

.husky/pre-commit

Husky run test was giving errors

MR-129: delete husky run test

---

.husky/pre-commit
src/controllers/admins.js
src/controllers/members.js
src/controllers/super-admins.js
src/helper/firebase/index.js
src/models/Admin.js
src/models/Member.js
src/models/SuperAdmin.js

-Implement Scheme and controllers to admin.
WIP:
-Still pendent to finish members and Super Admin

BaSP-MR-122: Schemes and controllers

---

package.json
src/controllers/admins.js
src/controllers/auth.js
src/controllers/members.js
src/controllers/trainers.js
src/middlewares/authMiddleware.js
src/routes/index.js

implementation for a new library and a little fix in how we get the user when logged

BaSP-MR-137: date-fns implementation

---

src/routes/index.js
src/routes/members.js

POST members doesn't require a token anymore

MR-137: verifytoken in members

---

src/controllers/classes.js
src/models/Class.js
src/routes/index.js
src/seeds/classes.js
src/validations/classes.js

Class subscribers will be an array with the members subscribed to that class and gonna replace the "slots"

MR-141: classes validations

---

src/controllers/auth.js
src/controllers/trainers.js
src/models/Trainer.js
src/seeds/trainers.js
src/validations/trainers.js

I added activitities to trainers and populated them

BaSP-MR-142: Add activities to trainers and populate

---

src/controllers/auth.js
src/controllers/subscriptions.js
src/validations/trainers.js

- Get auth trainer fixed
- Trainer's activities JOI validations
- Subscribe message
- Unsuscribe message

BaSP-MR-153: Trainers & Subs fixes
